In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
X_train

array([[ 1.92427584,  0.99224259,  1.92665152, ...,  1.49429438,
         0.35447745, -0.28137164],
       [-1.14204954,  0.46874809, -1.16438411, ..., -1.3575335 ,
        -0.86118475, -0.16141253],
       [-1.22299378, -0.02719406, -1.21582652, ..., -1.04719978,
         0.46399656, -0.19083646],
       ...,
       [-0.71765437, -1.1017354 , -0.69650314, ..., -0.6876141 ,
        -0.89247592, -0.12010585],
       [ 0.47402479,  0.84300074,  0.57118483, ...,  1.38467401,
         0.58603215,  2.36168964],
       [ 0.1367571 ,  0.52614881,  0.23272643, ...,  2.41448788,
         2.13494537,  2.49183396]])

In [8]:
y_train

250    M
425    B
424    B
292    B
30     M
      ..
409    B
259    M
540    B
118    M
26     M
Name: diagnosis, Length: 455, dtype: object

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
y_train

array([1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,

In [11]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [12]:
X_train_tensor.shape

torch.Size([455, 30])

In [13]:
y_train_tensor.shape

torch.Size([455])

# Here, we are using Dataset and DataLoader, which are very important for training a model efficiently.

## A Dataset is responsible for:

## Storing the data (features and labels).

## Defining how to access one sample of data using an index.

## Preprocessing or transforming the data if needed.

## In simple words, Dataset tells:
## 👉 “What is my data and how do I get one item from it?”

## A DataLoader is responsible for:

## Dividing the dataset into small groups called batches.

## Shuffling the data (if required).

## Loading data efficiently during training.

## In simple words, DataLoader tells:
## 👉 “How should I give the data to the model?”

# Why do we need batches?

## Instead of giving the whole dataset to the model at once:

## 1. It would require too much memory.

## 2. Training would be slow.

## So we divide data into small batches (like 32, 64, etc.).
## The model trains on one batch at a time.

In [15]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return len(self.features)

  def __getitem__(self, idx):

    return self.features[idx], self.labels[idx]



In [16]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [17]:
train_dataset[10]

(tensor([ 1.5336,  2.1885,  1.7103,  1.5374, -0.2640,  1.9798,  1.1499,  1.6979,
          0.3080, -0.0621,  1.5071,  0.0056,  2.0606,  1.3588, -0.2311,  1.2593,
          0.2112,  0.5318, -0.1473,  0.5464,  1.8015,  1.7265,  2.1099,  1.7915,
         -0.1813,  1.8628,  0.7684,  1.2411, -0.1274,  0.9641]),
 tensor(1.))

In [18]:
# Here, we are using DataLoader to create batches. Here 32 means, create 32 batches of data from whole dataset and shuffle means random dataset.
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

# Define the model

In [19]:
import torch.nn as nn
class MyModel(nn.Module):

    def __init__(self, features):

        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(features, 20),
            nn.ReLU(),
            nn.Linear(20, 10),
            nn.ReLU(),
            nn.Linear(10, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.network(x)

# Important Parameters

In [20]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [21]:
# define loss function
loss_function = nn.BCELoss()

In [25]:
# Here, we will another loop for batches of dataset.
model = MyModel(X_train_tensor.shape[1])
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(epochs):

    for batch_features, batch_labels in train_loader:


        # forward pass
        y_pred = model(batch_features)

        # loss calculate
        loss = loss_function(y_pred, batch_labels.view(-1, 1))

        # clear grads for efficient compute gradients
        optimizer.zero_grad()

        # backward pass
        loss.backward()

        # calculating optimization and update parameters
        optimizer.step()

        #print each loss
    print("Epochs:", {epoch+1}, "Loss:{loss:.4f}".format(loss=loss.item()))



Epochs: {1} Loss:0.0000
Epochs: {2} Loss:1.6368
Epochs: {3} Loss:0.0079
Epochs: {4} Loss:0.0004
Epochs: {5} Loss:0.1540
Epochs: {6} Loss:0.0166
Epochs: {7} Loss:0.8200
Epochs: {8} Loss:0.0003
Epochs: {9} Loss:0.0001
Epochs: {10} Loss:0.0000
Epochs: {11} Loss:0.0000
Epochs: {12} Loss:0.0011
Epochs: {13} Loss:0.0001
Epochs: {14} Loss:0.0002
Epochs: {15} Loss:0.0000
Epochs: {16} Loss:0.0000
Epochs: {17} Loss:0.0000
Epochs: {18} Loss:0.0000
Epochs: {19} Loss:0.0150
Epochs: {20} Loss:0.0000
Epochs: {21} Loss:0.0000
Epochs: {22} Loss:0.0002
Epochs: {23} Loss:0.0013
Epochs: {24} Loss:0.0000
Epochs: {25} Loss:0.0008


# Check Accuracy

In [24]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.5).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.9627
