In [5]:
import torch

In [9]:
# using empty
a = torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
type(a)

torch.Tensor

In [15]:
# using zeros and ones
zeros = torch.zeros(2,3)
ones = torch.ones(2,3, 2) # 3 dimensional
ones

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [16]:
# using random
random = torch.rand(2,3)

In [24]:
# using manual_seed. It's use for handle random values.
torch.manual_seed(32)
rn = torch.rand(3,2)
rn

tensor([[0.6147, 0.3810],
        [0.6371, 0.4745],
        [0.7136, 0.6190]])

In [26]:
# using tensor. With this, you create custom tensors.
custom = torch.tensor([[3,2,1], [2,31,2]])
custom

tensor([[ 3,  2,  1],
        [ 2, 31,  2]])

In [30]:
# using linspace (linear space), you can create data with evenly space.
lnsp = torch.linspace(0, 1, steps=5)
lnsp

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [37]:
# using shape
shape = torch.tensor([[2, 3,4],[2,3,4]])
shape.shape

torch.Size([2, 3])

## Mathematical Operations

In [40]:
x = torch.rand(2,3)
x

tensor([[0.3901, 0.9088, 0.5334],
        [0.7073, 0.7116, 0.2050]])

In [44]:
# add
x+2

# divide
x/2

# int division
(x*100)//2

# mod
((x*100)//2)%2

# power
x **2


tensor([[0.1521, 0.8260, 0.2845],
        [0.5003, 0.5064, 0.0420]])

In [47]:
# using clamp, you can range the values
v = torch.tensor([[1,2,-3,-4,5],[6,-7,8,-9,10]])
torch.clamp(v,min=0,max=7)

tensor([[1, 2, 0, 0, 5],
        [6, 0, 7, 0, 7]])

In [48]:
# using inplace method. It's use for perform operation in matrix itself. It'll not create new matrix. It's specially use for memory handling.

f = torch.tensor([[1,2,-3,-4,5],[6,-7,8,-9,10]])
h = torch.tensor([[3,4,5,1,6], [4,2,1,5,3]])

f.add_(h)

tensor([[ 4,  6,  2, -3, 11],
        [10, -5,  9, -4, 13]])

In [52]:
# using reshape


x = torch.tensor([1, 2, 3, 4, 5, 6])
x
y = x.reshape(2,3)
y

tensor([[1, 2, 3],
        [4, 5, 6]])

In [56]:
# unsqueeze: it adds a new dimension of size 1 at a specified position.
# squeeze:  it remove a new dimension of size 1 at a specified position.
x = torch.tensor([1, 2, 3, 4])
y = x.unsqueeze(1)
y.shape

torch.Size([4, 1])